// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckProductFromAdmin(ctx context.Context, arg CheckProductFromAdminParams) (uuid.UUID, error)
	CheckVariantFromAdmin(ctx context.Context, arg CheckVariantFromAdminParams) (uuid.UUID, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (CreateAdminRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (CreateVariantRow, error)
	DeleteProduct(ctx context.Context, argUuid uuid.UUID) error
	DeleteVariant(ctx context.Context, argUuid uuid.UUID) error
	GetAdmin(ctx context.Context, arg GetAdminParams) (GetAdminRow, error)
	GetProduct(ctx context.Context, argUuid uuid.UUID) (ProductView, error)
	GetProductForUpdate(ctx context.Context, argUuid uuid.UUID) (GetProductForUpdateRow, error)
	GetProductID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetVariant(ctx context.Context, argUuid uuid.UUID) (GetVariantRow, error)
	GetVariantForUpdate(ctx context.Context, argUuid uuid.UUID) (GetVariantForUpdateRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ProductView, error)
	ListVariants(ctx context.Context, arg ListVariantsParams) ([]ListVariantsRow, error)
	UpdateAProduct(ctx context.Context, arg UpdateAProductParams) (UpdateAProductRow, error)
	UpdateAVariant(ctx context.Context, arg UpdateAVariantParams) (UpdateAVariantRow, error)
}

var _ Querier = (*Queries)(nil)
